mode: backfill
history_days: 7
database:
  db_url: "sqlite:///db.sqlite3"
# ... (інші ваші налаштування)

openai:
  timeout: 30
  concurrency: 5
  stage_one:
    model: gpt-4o-mini # або інша швидка модель
    max_retries: 1
    system_prompt: >
      You are an AI pre-screener. Your primary goal is to identify ANY message where a user is discussing a technical problem, asking for development help, or inquiring about a project.
      - Your verdict MUST be "POTENTIAL" if the message is a question about code, a technical issue, a project idea, a request for consultation, or any form of request for help related to software development.
      - Your verdict MUST be "JUNK" ONLY if it is 100% clear that the message is offtopic, spam, a greeting, or a conversation completely unrelated to technology or development.
      - **Crucial rule: If a message contains a question about a programming language, a framework, an error, or a technical task, you MUST classify it as "POTENTIAL".** Do not filter out simple questions. Your job is to pass everything that could lead to a technical conversation.

  stage_two:
    model: gpt-4o-mini # або інша потужна модель
    temperature: 0.0
    max_retries: 3
    system_prompt: >
      You are an expert AI analyst. The following message has been pre-filtered as potentially relevant. Your task is to determine if it is an actionable, PAID opportunity.
      1.  **Analyze the Intent:** Is the user asking a general question (seeking free knowledge) or are they describing a problem that implies a need for a paid solution (a project, urgent task, consultation)?
      2.  **Classify Confidence & Verdict:**
          - RELEVANT: A clear offer of paid work or a direct request for a paid project/consultation.
          - POSSIBLY_RELEVANT: The user describes a significant problem or project, strongly implying a need for paid help, but doesn't explicitly mention payment.
          - POSSIBLY_UNRELEVANT: The user asks a technical question. It *could* be part of a larger project, but it's more likely a request for free community help.
          - UNRELEVANT: This is clearly a student's homework, a simple question with no business context, or a request for free mentorship.
      3.  **Provide Details:** If it's a lead, classify its type, provide a summary, and extract the tech stack.

discord:
  concurrent_channels: 10
  batch_pause_seconds: 0.5
  delay_seconds:
  - 0.1
  - 0.3
  message_page_limit: 100
  max_retries: 5
  track_all_channels: true
  channel_whitelist: []
google_sheet:
  spreadsheet_id: 14ISINuyVNeu8FBK908W6unARlFrj7fG542JIW_tK8Iw
  live_sheet_name: Live
  backfill_sheet_name: Previous
  stats_sheet_name: Stats
  leads_sheet_name: Leads
  write_mode: all
export:
  status_map:
    RELEVANT: 🔥 Hot Lead
    POSSIBLY_RELEVANT: 💡 Good Lead
    POSSIBLY_UNRELEVANT: 🤔 Possible
    UNRELEVANT: ❌ Not a Lead
    ERROR: ⚠️ Error
  lead_type_map:
    direct_hire: Direct Hire
    project_work: Project Work
    paid_help: Paid Help
    other: Other
  default_header:
  - Time
  - Server Name
  - Channel Name
  - Sender Name
  - Message Content
  - OpenAI Status
  - Score
  - Type
  - Manual Status
  - Message Link
keywords:
- looking for
- we need
- i need
- hire
- hiring
- paid opportunity
- paid project
- paid gig
- budget for
- have a budget
- quote for
- proposal for
- need a dev
- find a dev
- outsource
- commercial project
- contract work
- need help with
- can someone help
- struggling with
- assistance with
- stuck on
- issue with
- problem with
- any recommendations for
- guidance on
- who can
- need an expert
- looking for expertise
- build a
- create a
- develop a
- integrate
- migration
- migrating
- refactor
- optimize
- scaling
- debug
- maintain
- update a
- audit
- review my code
- developer
- engineer
- programmer
- team
- agency
- consultant
- expert
- specialist
- architect
- full-stack
- backend
- frontend
- devops
- mvp
- prototype
- startup
- platform
- app
- application
- website
- e-commerce
- marketplace
- automation
- script
- bot
- api
- backend
- interface
- python
- node.js
- java
- golang
- rust
- php
- react
- vue
- angular
- svelte
- javascript
- typescript
- swift
- kotlin
- flutter
- react native
- solidity
- smart contract
- dapp
- web3
- blockchain
- postgresql
- mysql
- mongodb
- database
- aws
- gcp
- azure
- docker
- kubernetes
- terraform
- pytorch
- tensorflow
- ai model
- machine learning
log_level: INFO
