# Головний конфігураційний файл
# Налаштування тут можуть бути перевизначені через змінні середовища
# (напр. export APP_MODE="live")

# Режим роботи: "backfill" (збирає історію) або "live" (слухає нові повідомлення)
mode: "backfill"
history_days: 1

# --- Загальні налаштування обробки ---
batch_size: 500
concurrency: 5                # Загальна паралельність у внутрішніх процесах
# --- ✅ НОВИЙ РОЗДІЛ ТУТ ---
database:
  db_url: "sqlite://db.sqlite3" # Шлях до вашої бази даних

# --- ✅ РОЗШИРЕНІ НАЛАШТУВАННЯ АГЕНТА ---
openai:
  model: "gpt-4o-mini"
  temperature: 0.0
  timeout: 45
  max_retries: 3
  system_prompt: |
    You are an expert Business Development Analyst for a top-tier software development agency. Your mission is to meticulously analyze Discord messages to identify high-quality business opportunities.

    Your primary goal is to distinguish between a user **expressing a NEED** for technical services (a potential lead) and a user **OFFERING** their own services (not a lead).

    **CRITICAL GUIDELINES:**
    1.  **IDENTIFY THE NEED:** A message is a lead ONLY if the user is actively looking for help. This includes seeking developers, needing a project built, or being stuck on a significant technical problem that implies paid work.
    2.  **IGNORE SELF-PROMOTION:** Explicitly reject any message where the user is advertising their skills, portfolio, or services. This is the most important rule.
    3.  **FILTER OUT NOISE:** Discard simple technical questions, requests for free help, unpaid collaborations, or general discussions. A true lead implies a clear intent for a transactional, project-based engagement.
    4.  **EXTRACT KEY DETAILS:** If you identify a lead, your task is to extract all possible business-critical information from the message: required technologies, potential budget indicators (e.g., "paid", "budget"), and any mentioned timelines or deadlines.

    Your final output MUST be a perfectly structured data object based on the user's request.
  user_prompt_template: "Analyze this message:\n\n---\n{message}\n---"
# --- Налаштування Discord ---
discord:
  concurrent_channels: 3
  batch_pause_seconds: 1
  delay_seconds: [0.1, 0.6]
  message_page_limit: 100
  max_retries: 5
  track_all_channels: true
  channel_whitelist: []         # Додайте ID каналів сюди, якщо track_all_channels = false

# --- Налаштування Google Sheets ---
google_sheet:
  spreadsheet_id: "14ISINuyVNeu8FBK908W6unARlFrj7fG542JIW_tK8Iw"
  live_sheet_name: "Live"
  backfill_sheet_name: "Previous"
  stats_sheet_name: "Stats"
  leads_sheet_name: "Leads"
  # Режим запису в Google Sheets: "all" (всі) або "qualified" (тільки RELEVANT та HIGH_MAYBE)
  write_mode: "qualified"
# --- ✅ НОВИЙ РОЗДІЛ ТУТ ---
# Налаштування для команди export
export:
  # Словник для красивого відображення статусів
  status_map:
    RELEVANT: "🔥 Hot Lead"
    HIGH_MAYBE: "💡 Good Lead"
    LOW_MAYBE: "🤔 Possible"
    UNRELEVANT: "❌ Not a Lead"
    ERROR: "⚠️ Error"
  # Словник для типів лідів
  lead_type_map:
    direct_hire: "Direct Hire"
    project_work: "Project Work"
    paid_help: "Paid Help"
    other: "Other"
  # Заголовки для нового аркуша "Leads"
  default_header:
    - "Time"
    - "Server Name"
    - "Channel Name"
    - "Sender Name"
    - "Message Content"
    - "OpenAI Status"
    - "Score"
    - "Type"
    - "Manual Status"
    - "Message Link"

# --- Ключові слова для пошуку бізнес-лідів (v4 - максимальне покриття) ---
keywords:
  # --- Прямий попит на послуги (максимальна пріоритетність) ---
  - "looking for"
  - "we need"
  - "i need"
  - "hire"
  - "hiring"
  - "paid opportunity"
  - "paid project"
  - "paid gig"
  - "budget for"
  - "have a budget"
  - "quote for"
  - "proposal for"
  - "need a dev"
  - "find a dev"
  - "outsource"
  - "commercial project"
  - "contract work"

  # --- Опис проблеми або потреби (широкий пошук) ---
  - "need help with"
  - "can someone help"
  - "struggling with"
  - "assistance with"
  - "stuck on"
  - "issue with"
  - "problem with"
  - "any recommendations for"
  - "guidance on"
  - "who can"
  - "need an expert"
  - "looking for expertise"

  # --- Дієслова, що вказують на роботу ---
  - "build a"
  - "create a"
  - "develop a"
  - "integrate"
  - "migration"
  - "migrating"
  - "refactor"
  - "optimize"
  - "scaling"
  - "debug"
  - "maintain"
  - "update a"
  - "audit"
  - "review my code"

  # --- Тип виконавця ---
  - "developer"
  - "engineer"
  - "programmer"
  - "team"
  - "agency"
  - "consultant"
  - "expert"
  - "specialist"
  - "architect"
  - "full-stack"
  - "backend"
  - "frontend"
  - "devops"

  # --- Тип проекту або продукту ---
  - "mvp"
  - "prototype"
  - "startup"
  - "platform"
  - "app"
  - "application"
  - "website"
  - "e-commerce"
  - "marketplace"
  - "automation"
  - "script"
  - "bot"
  - "api"
  - "backend"
  - "interface"

  # --- Технології та платформи (розширено) ---
  # Backend
  - "python"
  - "node.js"
  - "java"
  - "golang"
  - "rust"
  - "php"
  # Frontend
  - "react"
  - "vue"
  - "angular"
  - "svelte"
  - "javascript"
  - "typescript"
  # Mobile
  - "swift"
  - "kotlin"
  - "flutter"
  - "react native"
  # Web3/Blockchain
  - "solidity"
  - "smart contract"
  - "dapp"
  - "web3"
  - "blockchain"
  # Databases
  - "postgresql"
  - "mysql"
  - "mongodb"
  - "database"
  # DevOps/Cloud
  - "aws"
  - "gcp"
  - "azure"
  - "docker"
  - "kubernetes"
  - "terraform"
  # AI/ML
  - "pytorch"
  - "tensorflow"
  - "ai model"
  - "machine learning"